global using System.Data;
global using IZ.DockerDashboard.Application.Common.Interfaces;
global using IZ.DockerDashboard.Application.Common.Models;
global using IZ.DockerDashboard.Infrastructure.Extensions;
global using IZ.DockerDashboard.Domain.Entities;
// global using IZ.DockerDashboard.Components;
global using FluentValidation;
global using Microsoft.AspNetCore.Components;
global using MudBlazor;
global using Microsoft.EntityFrameworkCore;
global using AutoMapper;